version: "3.8"
services:
  nginx:
    image: nginx
    container_name: nginx
    links:
      - app1
      - app2
    ports:
      - "5000:80"
    volumes:
      - ./config/nginx:/etc/nginx/conf.d
  app1:
    build: ./app
    container_name: RediveBot1
    links:
      - mysql
      - redis
    env_file: ./.env
    environment:
      "PORT": 5001

  app2:
    build: ./app
    container_name: RediveBot2
    working_dir: /application
    links:
      - mysql
      - redis
    env_file: ./.env
    environment:
      "PORT": 5002

  mysql:
    env_file: ./.env
    image: mysql
    container_name: mysql
    volumes:
      - ./migration:/docker-entrypoint-initdb.d
      - "${DB_STOREPATH}/db:/var/lib/mysql"
    restart: always
    ports:
      - "3306:3306"
    environment:
      "MYSQL_DATABASE": "${DB_DATABASE}"
      "MYSQL_USER": "${DB_USER}"
      "MYSQL_PASSWORD": "${DB_USER_PASSWORD}"
      "MYSQL_ROOT_PASSWORD": "${DB_PASSWORD}"

  redis:
    image: redis:alpine
    container_name: redis
    command: "redis-server --requirepass ${REDIS_PASSWORD}"
    ports:
      - "6379:6379"