version: "3.5"
services:
  app:
    build: ./app
    env_file: ./.env
    restart: always
    ports:
      - "5000"
    depends_on:
      - mysql
      - redis
    networks:
      - nginx_network
      - bot_network
    environment:
      - "VIRTUAL_HOST=${APP_DOMAIN}"
      - "VIRTUAL_NETWORK=nginx-proxy"
      - "VIRTUAL_PORT=5000"
      - "LETSENCRYPT_HOST=${APP_DOMAIN}"
      - "LETSENCRYPT_EMAIL=${ADMIN_EMAIL}"

  mysql:
    env_file: ./.env
    image: mysql
    volumes:
      - ./migration:/docker-entrypoint-initdb.d
      - "${DB_STOREPATH}/db:/var/lib/mysql"
    restart: always
    expose:
      - "${DB_PORT}"
    networks:
      - bot_network
    environment:
      "MYSQL_DATABASE": "${DB_DATABASE}"
      "MYSQL_USER": "${DB_USER}"
      "MYSQL_PASSWORD": "${DB_USER_PASSWORD}"
      "MYSQL_ROOT_PASSWORD": "${DB_PASSWORD}"

  redis:
    image: redis:alpine
    command: "redis-server --requirepass ${REDIS_PASSWORD}"
    restart: always
    networks:
      - bot_network
    expose:
      - "${REDIS_PORT}"

  crontab:
    build: ./job
    networks:
      - bot_network
    depends_on:
      - mysql
      - redis
    env_file: ./.env

networks:
  nginx_network:
    external: true
    name: nginx_network
  bot_network:
