version: "3.5"
services:
  app:
    build: ./app
    links:
      - mysql
      - redis
    env_file: ./.env
    restart: always
    ports:
      - "5000"
    depends_on:
      - mysql
      - redis
    environment:
      - "VIRTUAL_HOST=${APP_DOMAIN}"
      - "VIRTUAL_NETWORK=nginx-proxy"
      - "VIRTUAL_PORT=5000"
      - "LETSENCRYPT_HOST=${APP_DOMAIN}"
      - "LETSENCRYPT_EMAIL=${ADMIN_EMAIL}"

  mysql:
    env_file: ./.env
    image: mysql
    container_name: mysql
    volumes:
      - ./migration:/docker-entrypoint-initdb.d
      - "${DB_STOREPATH}/db:/var/lib/mysql"
    restart: always
    ports:
      - "${DB_PORT}"
    environment:
      "MYSQL_DATABASE": "${DB_DATABASE}"
      "MYSQL_USER": "${DB_USER}"
      "MYSQL_PASSWORD": "${DB_USER_PASSWORD}"
      "MYSQL_ROOT_PASSWORD": "${DB_PASSWORD}"

  redis:
    image: redis:alpine
    container_name: redis
    command: "redis-server --requirepass ${REDIS_PASSWORD}"
    restart: always
    ports:
      - "${REDIS_PORT}"

  crontab:
    build: ./job
    container_name: redive_crontab
    links:
      - mysql
      - redis
    env_file: ./.env

  amqp:
    image: rabbitmq:3.8.9-management-alpine
    container_name: amqp
    restart: always

networks:
  default:
    external:
      name: nginx_network