version: "3.8"
services:
  nginx-proxy:
    container_name: nginx
    image: jwilder/nginx-proxy:alpine
    ports:
      - "5000:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    environment:
      - DEFAULT_HOST=redivebot.local
  app:
    build: ./app
    links:
      - mysql
      - redis
    env_file: ./.env
    ports:
      - "5000"
    environment:
      - VIRTUAL_HOST=redivebot.local

  mysql:
    env_file: ./.env
    image: mysql
    container_name: mysql
    volumes:
      - ./migration:/docker-entrypoint-initdb.d
      - "${DB_STOREPATH}/db:/var/lib/mysql"
    restart: always
    ports:
      - "3306:3306"
    environment:
      "MYSQL_DATABASE": "${DB_DATABASE}"
      "MYSQL_USER": "${DB_USER}"
      "MYSQL_PASSWORD": "${DB_USER_PASSWORD}"
      "MYSQL_ROOT_PASSWORD": "${DB_PASSWORD}"

  redis:
    image: redis:alpine
    container_name: redis
    command: "redis-server --requirepass ${REDIS_PASSWORD}"
    ports:
      - "6379:6379"

  crontab:
    build: ./job
    container_name: redive_crontab
    links:
      - mysql
      - redis
    env_file: ./.env